//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace primeraprueba.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("primeraprueba.RecursosLocalizables.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda.
        /// </summary>
        internal static string barrabusqueda {
            get {
                return ResourceManager.GetString("barrabusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Tag.
        /// </summary>
        internal static string btnAddTagRec {
            get {
                return ResourceManager.GetString("btnAddTagRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string btnBorrar {
            get {
                return ResourceManager.GetString("btnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Tag.
        /// </summary>
        internal static string btnBorrarTagRec {
            get {
                return ResourceManager.GetString("btnBorrarTagRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string btnCancelRec {
            get {
                return ResourceManager.GetString("btnCancelRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string btnconfirmarCon {
            get {
                return ResourceManager.GetString("btnconfirmarCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string btnEnviarRec {
            get {
                return ResourceManager.GetString("btnEnviarRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string btnIniciarCon {
            get {
                return ResourceManager.GetString("btnIniciarCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string btnIniciarSesionHome {
            get {
                return ResourceManager.GetString("btnIniciarSesionHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string btnRegistroHome {
            get {
                return ResourceManager.GetString("btnRegistroHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguir.
        /// </summary>
        internal static string btSeguir {
            get {
                return ResourceManager.GetString("btSeguir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reto.
        /// </summary>
        internal static string challengeUI {
            get {
                return ResourceManager.GetString("challengeUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        internal static string contrasenyaCon {
            get {
                return ResourceManager.GetString("contrasenyaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        internal static string contrasenyaConfirmarCon {
            get {
                return ResourceManager.GetString("contrasenyaConfirmarCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string contrasenyaLogin {
            get {
                return ResourceManager.GetString("contrasenyaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Olvidada.
        /// </summary>
        internal static string contrasenyaOlvidadaLogin {
            get {
                return ResourceManager.GetString("contrasenyaOlvidadaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string correoCon {
            get {
                return ResourceManager.GetString("correoCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string descripcionUI {
            get {
                return ResourceManager.GetString("descripcionUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingredientes.
        /// </summary>
        internal static string ingredientesRec {
            get {
                return ResourceManager.GetString("ingredientesRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string iniciarLogin {
            get {
                return ResourceManager.GetString("iniciarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string inicioLogin {
            get {
                return ResourceManager.GetString("inicioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Imagen.
        /// </summary>
        internal static string insertarImagenRec {
            get {
                return ResourceManager.GetString("insertarImagenRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string lblDesc {
            get {
                return ResourceManager.GetString("lblDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombreLogin {
            get {
                return ResourceManager.GetString("nombreLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la receta.
        /// </summary>
        internal static string nomRecetaRec {
            get {
                return ResourceManager.GetString("nomRecetaRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Recetas.
        /// </summary>
        internal static string numRecetasUI {
            get {
                return ResourceManager.GetString("numRecetasUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Seguidores.
        /// </summary>
        internal static string numSeguidoresUI {
            get {
                return ResourceManager.GetString("numSeguidoresUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasos a seguir.
        /// </summary>
        internal static string pasosRec {
            get {
                return ResourceManager.GetString("pasosRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string perfilToolStripMenuItem {
            get {
                return ResourceManager.GetString("perfilToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recetas Destacadas.
        /// </summary>
        internal static string recetasDestacadasHome {
            get {
                return ResourceManager.GetString("recetasDestacadasHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recetas.
        /// </summary>
        internal static string recetasToolStripMenuItem {
            get {
                return ResourceManager.GetString("recetasToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string registrarLogin {
            get {
                return ResourceManager.GetString("registrarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retos.
        /// </summary>
        internal static string retosHome {
            get {
                return ResourceManager.GetString("retosHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Olvidada.
        /// </summary>
        internal static string tituloCon {
            get {
                return ResourceManager.GetString("tituloCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios Destacados.
        /// </summary>
        internal static string usuariosDestacadosHome {
            get {
                return ResourceManager.GetString("usuariosDestacadosHome", resourceCulture);
            }
        }
    }
}
